"""Tree collective algorithm backed by MockNcclGroup topology.

Implements the binary / double-binary tree reduce-broadcast pattern used
by NCCL's ALGO_TREE. The tree topology (parent/child relationships) is
generated by the C++ MockNcclGroup binding, which replicates the NCCL
topology search algorithm for single-node and multi-node configurations.

Phase 1 — Reduce-up: leaves send to parents. A rank can only send after
  all its children have sent to it (all incoming reduces completed).
Phase 2 — Broadcast-down: root sends to children. A rank can only send
  after it has received from its parent.
"""

from __future__ import annotations

from simulon.collective.common import P2PFlow


def _infer_gpus_per_node(group_ranks: list[int]) -> int:
    """Infer GPUs-per-node from the rank spacing pattern."""
    N = len(group_ranks)
    if N <= 1:
        return N
    strides = [group_ranks[i + 1] - group_ranks[i] for i in range(N - 1)]
    min_stride = min(strides)
    if min_stride == 1:
        # Consecutive ranks — assume at most 8 GPUs per node (H100 default)
        return min(N, 8)
    else:
        # DP/PP-like pattern: stride = gpus_per_node
        return min_stride


def _get_tree_topology(
    N: int, num_nodes: int, gpus_per_node: int, num_channels: int
) -> dict[int, dict[int, tuple[int, list[int]]]]:
    """Query MockNcclGroup for the tree channel topology.

    Returns: {channel_id: {internal_rank: (parent_rank, [child_ranks])}}
    where -1 means no parent (root). Uses only the first num_channels channels.
    """
    try:
        import simulon._mocknccl as _m

        # NVSwitch IDs: one virtual switch per node, indexed beyond GPU ranks
        nvswitches = [N + i for i in range(num_nodes)]
        g = _m.MockNcclGroup(
            N,
            gpus_per_node,
            N,
            1,
            1,
            1,
            1,  # tp=N, dp=pp=ep=dp_ep=1
            nvswitches,
            _m.GPUType.H100,
        )
        raw = g.gettreechannels(0, _m.GroupType.TP)
    except Exception as exc:
        raise RuntimeError(f"Failed to build tree topology via MockNcclGroup: {exc}") from exc

    ch_ids = sorted(raw.keys())[:num_channels]
    topology: dict[int, dict[int, tuple[int, list[int]]]] = {}
    for ch_id in ch_ids:
        topology[ch_id] = {}
        for rank, tree in raw[ch_id].items():
            topology[ch_id][rank] = (tree.up, list(tree.down))
    return topology


def _reduce_order(topo: dict[int, tuple[int, list[int]]]) -> list[int]:
    """Return ranks in leaves-first order for the reduce-up phase.

    Performs a BFS from the root and reverses the result so leaves come first.
    """
    root = next(r for r, (p, _) in topo.items() if p == -1)
    visited: list[int] = []
    queue = [root]
    while queue:
        cur = queue.pop(0)
        visited.append(cur)
        _, children = topo[cur]
        queue.extend(children)
    return list(reversed(visited))


def tree_all_reduce(
    group_ranks: list[int], data_size: int, num_channels: int = 1, flow_id_start: int = 0
) -> tuple[list[P2PFlow], int]:
    """Tree AllReduce across group_ranks using NCCL double-binary tree topology.

    The tree topology is queried from the C++ MockNcclGroup binding, which
    replicates NCCL's actual channel layout. Multiple channels share the
    total data (each carries data_size // num_channels bytes) and run
    concurrently with potentially different root assignments for load balancing.

    Dependency model:
    - Reduce-up: rank i's send to its parent depends on all children of i
      having sent to i first (all children's reduce flows must complete).
    - Broadcast-down: rank i's send to child j depends on i's parent having
      sent to i (parent's broadcast flow must complete before i can forward).
    - Broadcast at root: root's sends to children depend on the last
      reduce-up flow arriving at root (root's own children's reduce flows).
    """
    N = len(group_ranks)
    if N == 1:
        return [], flow_id_start

    gpus_per_node = _infer_gpus_per_node(group_ranks)
    num_nodes = max(1, N // gpus_per_node)
    topology = _get_tree_topology(N, num_nodes, gpus_per_node, num_channels)

    chunk_size = data_size // num_channels
    chunk_count = num_channels

    fid = flow_id_start
    all_flows: list[P2PFlow] = []

    for ch_idx, (ch_id, ch_topo) in enumerate(topology.items()):
        # ---------------------------------------------------------------
        # Build reduce-up phase
        # ---------------------------------------------------------------
        # reduce_flow_ids[internal_rank] = flow_id of the flow that THIS
        # rank *sent* to its parent (i.e., the flow arriving at parent from rank).
        reduce_flow_ids: dict[int, int] = {}

        order = _reduce_order(ch_topo)

        for internal_rank in order:
            parent, children = ch_topo[internal_rank]
            if parent == -1:
                # Root — no outgoing reduce flow
                continue

            # This rank sends to its parent.
            # Dependency: all children of this rank must have sent to this rank.
            parent_flow_ids = [reduce_flow_ids[c] for c in children if c in reduce_flow_ids]

            src = group_ranks[internal_rank]
            dst = group_ranks[parent]
            flow = P2PFlow(
                flow_id=fid,
                src=src,
                dst=dst,
                flow_size=chunk_size,
                parent_flow_ids=parent_flow_ids,
                child_flow_ids=[],
                channel_id=ch_id,
                chunk_id=ch_idx,
                chunk_count=chunk_count,
                conn_type="TREE",
            )
            reduce_flow_ids[internal_rank] = fid
            all_flows.append(flow)
            fid += 1

        # ---------------------------------------------------------------
        # Build broadcast-down phase
        # ---------------------------------------------------------------
        # bcast_flow_ids[internal_rank] = flow_id of the flow that THIS
        # rank *received* from its parent in the broadcast phase.
        bcast_flow_ids: dict[int, int] = {}

        root = next(r for r, (p, _) in ch_topo.items() if p == -1)
        _, root_children = ch_topo[root]

        # Root's broadcast sends depend on the last reduce flow arriving at root
        # (i.e., all children's reduce flows).
        root_reduce_deps = [reduce_flow_ids[c] for c in root_children if c in reduce_flow_ids]

        # BFS top-down
        queue = [root]
        while queue:
            cur = queue.pop(0)
            _, children = ch_topo[cur]
            for child in children:
                parent_bcast_fid = bcast_flow_ids.get(cur)
                # Root's sends depend on reduce-up completing; other sends depend
                # on parent's broadcast send completing.
                if cur == root:
                    deps = root_reduce_deps
                else:
                    deps = [parent_bcast_fid] if parent_bcast_fid is not None else []

                src = group_ranks[cur]
                dst = group_ranks[child]
                flow = P2PFlow(
                    flow_id=fid,
                    src=src,
                    dst=dst,
                    flow_size=chunk_size,
                    parent_flow_ids=deps,
                    child_flow_ids=[],
                    channel_id=ch_id,
                    chunk_id=ch_idx,
                    chunk_count=chunk_count,
                    conn_type="TREE",
                )
                bcast_flow_ids[child] = fid
                all_flows.append(flow)
                fid += 1

            queue.extend(children)

    # Back-fill child_flow_ids from parent_flow_ids
    fid_to_flow = {f.flow_id: f for f in all_flows}
    for flow in all_flows:
        for pid in flow.parent_flow_ids:
            parent_flow = fid_to_flow.get(pid)
            if parent_flow and flow.flow_id not in parent_flow.child_flow_ids:
                parent_flow.child_flow_ids.append(flow.flow_id)

    return all_flows, fid
