"""Tests for DAG nodes, pipeline scheduler, and layer expander."""

import pytest

from simulon.backend.dag.nodes import (
    ComputeNode,
    CommNode,
    DAGEdge,
    ExecutionDAG,
)
from simulon.backend.dag.pipeline import PipelineScheduler, ScheduleSlot
from simulon.backend.dag.layer_expander import LayerExpander


# ---------------------------------------------------------------------------
# PipelineScheduler
# ---------------------------------------------------------------------------


def test_pipeline_scheduler_pp1_all_fwd_then_bwd():
    """pp=1, nm=4: warmup=0, steady=4 fwd+bwd pairs → 8 slots."""
    sched = PipelineScheduler(pp=1, num_microbatches=4)
    slots = sched.schedule_for_stage(0)
    assert len(slots) == 8
    directions = [s.direction for s in slots]
    # Should be [fwd, bwd, fwd, bwd, fwd, bwd, fwd, bwd]
    for i, d in enumerate(directions):
        assert d == "fwd" if i % 2 == 0 else d == "bwd"


def test_pipeline_scheduler_pp4_stage0_warmup():
    """Stage 0 in pp=4 has warmup = pp-0-1 = 3 forward slots."""
    sched = PipelineScheduler(pp=4, num_microbatches=8)
    slots = sched.schedule_for_stage(0)
    fwd_mb = [s for s in slots if s.direction == "fwd"]
    bwd_mb = [s for s in slots if s.direction == "bwd"]
    assert len(fwd_mb) == 8
    assert len(bwd_mb) == 8


def test_pipeline_scheduler_pp4_last_stage_no_warmup():
    """Last stage (stage=pp-1=3) has warmup=0."""
    sched = PipelineScheduler(pp=4, num_microbatches=4)
    slots = sched.schedule_for_stage(3)
    # warmup=0, steady=4 pairs: fwd, bwd, fwd, bwd, fwd, bwd, fwd, bwd
    assert slots[0].direction == "fwd"
    assert slots[1].direction == "bwd"


def test_pipeline_scheduler_all_microbatches_covered():
    """All microbatches appear in both fwd and bwd slots."""
    nm = 6
    sched = PipelineScheduler(pp=3, num_microbatches=nm)
    for stage in range(3):
        slots = sched.schedule_for_stage(stage)
        fwd_mbs = sorted(s.microbatch_id for s in slots if s.direction == "fwd")
        bwd_mbs = sorted(s.microbatch_id for s in slots if s.direction == "bwd")
        assert fwd_mbs == list(range(nm))
        assert bwd_mbs == list(range(nm))


def test_pipeline_scheduler_slot_pipeline_stage():
    """Each slot's pipeline_stage matches the requested stage."""
    sched = PipelineScheduler(pp=2, num_microbatches=4)
    for stage in range(2):
        for slot in sched.schedule_for_stage(stage):
            assert slot.pipeline_stage == stage


# ---------------------------------------------------------------------------
# LayerExpander
# ---------------------------------------------------------------------------


def test_layer_expander_fwd_tp1_no_comm():
    """fwd phase, tp=1: no comm nodes, 4 compute nodes (attn)."""
    exp = LayerExpander()
    c_nodes, comm_nodes, edges, nid = exp.expand_sublayer(
        sublayer_type="attn",
        phase="fwd",
        gpu_rank=0,
        pipeline_stage=0,
        microbatch_id=0,
        layer_idx=0,
        tp_group_ranks=[0],
        activation_bytes=4096,
        node_id_start=0,
    )
    assert len(comm_nodes) == 0
    assert len(c_nodes) == 4  # layernorm, attn_qkv, attn_flash, attn_proj
    assert nid == 4


def test_layer_expander_fwd_tp2_has_ag_rs():
    """fwd phase, tp=2: AllGather + compute nodes + ReduceScatter."""
    exp = LayerExpander()
    c_nodes, comm_nodes, edges, nid = exp.expand_sublayer(
        sublayer_type="attn",
        phase="fwd",
        gpu_rank=0,
        pipeline_stage=0,
        microbatch_id=0,
        layer_idx=0,
        tp_group_ranks=[0, 1],
        activation_bytes=4096,
        node_id_start=0,
    )
    assert len(comm_nodes) == 2
    assert comm_nodes[0].collective_type == "AllGather"
    assert comm_nodes[1].collective_type == "ReduceScatter"
    assert len(c_nodes) == 4
    # nid = 1 (AG) + 4 (kernels) + 1 (RS) = 6
    assert nid == 6


def test_layer_expander_bwd_ig_tp2_has_ag_rs():
    """bwd_ig phase, tp=2: same pattern as fwd."""
    exp = LayerExpander()
    _, comm_nodes, _, _ = exp.expand_sublayer(
        sublayer_type="mlp",
        phase="bwd_ig",
        gpu_rank=0,
        pipeline_stage=0,
        microbatch_id=0,
        layer_idx=0,
        tp_group_ranks=[0, 1],
        activation_bytes=4096,
        node_id_start=0,
    )
    types = [n.collective_type for n in comm_nodes]
    assert "AllGather" in types
    assert "ReduceScatter" in types


def test_layer_expander_bwd_wg_no_comm():
    """bwd_wg phase, tp=2: no comm nodes generated by expander."""
    exp = LayerExpander()
    _, comm_nodes, _, _ = exp.expand_sublayer(
        sublayer_type="attn",
        phase="bwd_wg",
        gpu_rank=0,
        pipeline_stage=0,
        microbatch_id=0,
        layer_idx=0,
        tp_group_ranks=[0, 1],
        activation_bytes=4096,
        node_id_start=0,
    )
    assert len(comm_nodes) == 0


def test_layer_expander_edges_connect_nodes():
    """Edges connect sequential nodes."""
    exp = LayerExpander()
    c_nodes, comm_nodes, edges, _ = exp.expand_sublayer(
        sublayer_type="attn",
        phase="fwd",
        gpu_rank=0,
        pipeline_stage=0,
        microbatch_id=0,
        layer_idx=0,
        tp_group_ranks=[0, 1],
        activation_bytes=4096,
        node_id_start=10,
    )
    # Should have edges between sequential nodes
    assert len(edges) > 0
    # First edge from AG (nid=10) to first compute node (nid=11)
    assert edges[0].src_node_id == 10
    assert edges[0].dst_node_id == 11


def test_layer_expander_node_id_continuity():
    """node_id_start is honoured and nid advances correctly."""
    exp = LayerExpander()
    _, _, _, nid = exp.expand_sublayer(
        sublayer_type="mlp",
        phase="fwd",
        gpu_rank=0,
        pipeline_stage=0,
        microbatch_id=0,
        layer_idx=0,
        tp_group_ranks=[0, 1],
        activation_bytes=4096,
        node_id_start=50,
    )
    # AG(1) + kernels(4) + RS(1) = 6 nodes
    assert nid == 56


def test_layer_expander_mlp_kernels():
    """MLP attn has 4 kernels: layernorm, mlp_linear1, mlp_act, mlp_linear2."""
    exp = LayerExpander()
    c_nodes, _, _, _ = exp.expand_sublayer(
        sublayer_type="mlp",
        phase="fwd",
        gpu_rank=0,
        pipeline_stage=0,
        microbatch_id=0,
        layer_idx=0,
        tp_group_ranks=[0],
        activation_bytes=4096,
        node_id_start=0,
    )
    kernels = [n.kernel for n in c_nodes]
    assert kernels == ["layernorm", "mlp_linear1", "mlp_act", "mlp_linear2"]


# ---------------------------------------------------------------------------
# ExecutionDAG serialization
# ---------------------------------------------------------------------------


def test_execution_dag_to_dict():
    dag = ExecutionDAG(
        compute_nodes=[ComputeNode(0, 0, "layernorm", 0, 0, 0, "fwd")],
        comm_nodes=[CommNode(1, 0, 1, 512, "AllGather", 0, "fwd", 0)],
        edges=[DAGEdge(0, 1)],
    )
    d = dag.to_dict()
    assert len(d["compute_nodes"]) == 1
    assert len(d["comm_nodes"]) == 1
    assert len(d["edges"]) == 1
    assert d["compute_nodes"][0]["kernel"] == "layernorm"


def test_execution_dag_to_json():
    import json
    dag = ExecutionDAG(
        compute_nodes=[ComputeNode(0, 0, "layernorm", 0, 0, 0, "fwd")],
    )
    j = dag.to_json()
    data = json.loads(j)
    assert data["compute_nodes"][0]["gpu_rank"] == 0
