framework: megatron
config:
  num-gpus: 1024
  disable-bias-linear: true
  no-bias-dropout-fusion: true
  tensor-model-parallel-size: 2
  pipeline-model-parallel-size: 8
  sequence-parallel: true
  expert-model-parallel-size: 64
  expert-tensor-parallel-size: 1
  bf16: true
  cross-entropy-loss-fusion: true
  cross-entropy-fusion-impl: te
  num-layers: 61
  mtp-num-layers: 1
  pipeline-model-parallel-layout: Et|(tt|)*30mL
  hidden-size: 7168
  num-attention-heads: 128
  num-query-groups: 128
  ffn-hidden-size: 18432
  kv-channels: 64
  hidden-dropout: 0
  attention-dropout: 0
  norm-epsilon: 1.0e-06
  num-experts: 256
  normalization: RMSNorm
  qk-layernorm: true
  multi-latent-attention: true
  init-method-std: 0.006
  attention-softmax-in-fp32: false
  recompute-granularity: selective
  recompute-modules:
  - mla_up_proj
  - mlp
  moe-shared-expert-intermediate-size: 2048
  moe-layer-freq: '[0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]'
  moe-ffn-hidden-size: 2048
  moe-router-topk: 8
  moe-router-num-groups: 8
  moe-router-group-topk: 4
  moe-router-pre-softmax: true
  moe-router-topk-scaling-factor: 2.5
  moe-router-score-function: sigmoid
  moe-router-dtype: fp32
  moe-router-enable-expert-bias: true
  moe-grouped-gemm: true
  moe-aux-loss-coeff: 0.0001
  moe-token-dispatcher-type: alltoall
  moe-flex-dispatcher-backend: hybridep
  moe-permute-fusion: true
  moe-router-fusion: true
  moe-hybridep-num-sms: 32
  q-lora-rank: 1536
  mscale-all-dim: 1
  share-embeddings-and-output-weights: false
  make-vocab-size-divisible-by: 1280
  position-embedding-type: rope
  seq-length: 4096
  vocab-size: 32000
  grad-reduce-in-bf16: false
  fp8-format: hybrid
  fp8-param-gather: true
  num-layers-at-start-in-bf16: 1
  num-layers-at-end-in-bf16: 1
  lr: 0.0003
  min-lr: 3.0e-05
  use-precision-aware-optimizer: true
  main-grads-dtype: bf16
  exp-avg-dtype: bf16
  exp-avg-sq-dtype: bf16
  adam-beta2: 0.95
  use-distributed-optimizer: true
  overlap-grad-reduce: true
  overlap-param-gather: true
  micro-batch-size: 1
  global-batch-size: 8192
  manual-gc: true
  manual-gc-interval: 5
  override-opt-param-scheduler: true
  num-workers: 8
  seed: 1234
  split: 1000,0,0
  reset-position-ids: false
  reset-attention-mask: false
  eod-mask-loss: false
  tokenizer-type: NullTokenizer
  fp8-recipe: tensorwise
  mock-data: true
